package net.applee.minecraft.world;

public enum ParticleType {
	AMBIENT_ENTITY_EFFECT("ambient_entity_effect"),
	ANGRY_VILLAGER("angry_villager"),
	BLOCK("block"),
	BLOCK_MARKER("block_marker"),
	BUBBLE("bubble"),
	CLOUD("cloud"),
	CRIT("crit"),
	DAMAGE_INDICATOR("damage_indicator"),
	DRAGON_BREATH("dragon_breath"),
	DRIPPING_LAVA("dripping_lava"),
	FALLING_LAVA("falling_lava"),
	LANDING_LAVA("landing_lava"),
	DRIPPING_WATER("dripping_water"),
	FALLING_WATER("falling_water"),
	DUST("dust"),
	DUST_COLOR_TRANSITION("dust_color_transition"),
	EFFECT("effect"),
	ELDER_GUARDIAN("elder_guardian"),
	ENCHANTED_HIT("enchanted_hit"),
	ENCHANT("enchant"),
	END_ROD("end_rod"),
	ENTITY_EFFECT("entity_effect"),
	EXPLOSION_EMITTER("explosion_emitter"),
	EXPLOSION("explosion"),
	SONIC_BOOM("sonic_boom"),
	FALLING_DUST("falling_dust"),
	FIREWORK("firework"),
	FISHING("fishing"),
	FLAME("flame"),
	SCULK_SOUL("sculk_soul"),
	SCULK_CHARGE("sculk_charge"),
	SCULK_CHARGE_POP("sculk_charge_pop"),
	SOUL_FIRE_FLAME("soul_fire_flame"),
	SOUL("soul"),
	FLASH("flash"),
	HAPPY_VILLAGER("happy_villager"),
	COMPOSTER("composter"),
	HEART("heart"),
	INSTANT_EFFECT("instant_effect"),
	ITEM("item"),
	VIBRATION("vibration"),
	ITEM_SLIME("item_slime"),
	ITEM_SNOWBALL("item_snowball"),
	LARGE_SMOKE("large_smoke"),
	LAVA("lava"),
	MYCELIUM("mycelium"),
	NOTE("note"),
	POOF("poof"),
	PORTAL("portal"),
	RAIN("rain"),
	SMOKE("smoke"),
	SNEEZE("sneeze"),
	SPIT("spit"),
	SQUID_INK("squid_ink"),
	SWEEP_ATTACK("sweep_attack"),
	TOTEM_OF_UNDYING("totem_of_undying"),
	UNDERWATER("underwater"),
	SPLASH("splash"),
	WITCH("witch"),
	BUBBLE_POP("bubble_pop"),
	CURRENT_DOWN("current_down"),
	BUBBLE_COLUMN_UP("bubble_column_up"),
	NAUTILUS("nautilus"),
	DOLPHIN("dolphin"),
	CAMPFIRE_COSY_SMOKE("campfire_cosy_smoke"),
	CAMPFIRE_SIGNAL_SMOKE("campfire_signal_smoke"),
	DRIPPING_HONEY("dripping_honey"),
	FALLING_HONEY("falling_honey"),
	LANDING_HONEY("landing_honey"),
	FALLING_NECTAR("falling_nectar"),
	FALLING_SPORE_BLOSSOM("falling_spore_blossom"),
	ASH("ash"),
	CRIMSON_SPORE("crimson_spore"),
	WARPED_SPORE("warped_spore"),
	SPORE_BLOSSOM_AIR("spore_blossom_air"),
	DRIPPING_OBSIDIAN_TEAR("dripping_obsidian_tear"),
	FALLING_OBSIDIAN_TEAR("falling_obsidian_tear"),
	LANDING_OBSIDIAN_TEAR("landing_obsidian_tear"),
	REVERSE_PORTAL("reverse_portal"),
	WHITE_ASH("white_ash"),
	SMALL_FLAME("small_flame"),
	SNOWFLAKE("snowflake"),
	DRIPPING_DRIPSTONE_LAVA("dripping_dripstone_lava"),
	FALLING_DRIPSTONE_LAVA("falling_dripstone_lava"),
	DRIPPING_DRIPSTONE_WATER("dripping_dripstone_water"),
	FALLING_DRIPSTONE_WATER("falling_dripstone_water"),
	GLOW_SQUID_INK("glow_squid_ink"),
	GLOW("glow"),
	WAX_ON("wax_on"),
	WAX_OFF("wax_off"),
	ELECTRIC_SPARK("electric_spark"),
	SCRAPE("scrape"),
	SHRIEK("shriek");

	private final String name;

	ParticleType(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}
}
